### ISSUE TITLE
In ANFW-centralized-2az-template.yaml line 732 is duplicate of 685

### ISSUE THREAD

**Issue by niteenkole** [aws-samples/aws-networkfirewall-cfn-templates#2]
in ANFW-centralized-2az-template.yaml line 732 is duplicate of 685

Looks like it should be 

685 -->
  SubnetCFirewallADefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachVPCC
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      TransitGatewayId: !Ref TransitGateway
      RouteTableId: !Ref SubnetCFirewallRouteTableA

732
  SubnetCFirewallADefaultRoute:   --->this should be SubnetCFirewall**B**DefaultRoute 
    Type: AWS::EC2::Route
    DependsOn: AttachVPCC
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      TransitGatewayId: !Ref TransitGateway
      RouteTableId: !Ref SubnetCFirewallRouteTableB

**Comment by pmankad96** [comment]
Fixed. Resolving the issue. Thanks.
