### ISSUE TITLE
Question on egress firewall

### ISSUE THREAD

**Issue by niteenkole** [aws-samples/aws-networkfirewall-cfn-templates#3]
Hi thanks for putting this detail tests, very  helpful.

Question:
Your diagram for centralized setup don't show any Network firewall but in ANFW-centralized-2az-template.yaml setup we see setting NFW in inspection VPC as well as  egress VPC.

Question is in ANFW-centralized-2az-template.yaml we have to setup NFW in inspection as well as egress VPC or am I misunderstanding ?

**Comment by pmankad96** [comment]
Correct. Centralized deployment (single and multi AZ) creates dedicated Inspection VPC for inter-VPC traffic inspection and Central Egress VPC for Spoke VPC to Internet traffic inspection. NFW is created for each dedicated VPC. Updated centralized architecture with appropriate diagrams/topology and description.
